# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'message_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15message_service.proto\x12\x07message\"\x1c\n\tABRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\" \n\nABResponse\x12\x12\n\ngroup_name\x18\x01 \x01(\t\"\"\n\x10\x46\x61\x63torialRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"#\n\x11\x46\x61\x63torialResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\".\n\x0eLetterResponse\x12\x1c\n\x14most_frequent_letter\x18\x01 \x01(\t2\xd0\x01\n\x10\x41\x42TestingService\x12\x33\n\x08\x41ssignAB\x12\x12.message.ABRequest\x1a\x13.message.ABResponse\x12\x42\n\tFactorial\x12\x19.message.FactorialRequest\x1a\x1a.message.FactorialResponse\x12\x43\n\x12MostFrequentLetter\x12\x14.message.TextRequest\x1a\x17.message.LetterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ABREQUEST']._serialized_start=34
  _globals['_ABREQUEST']._serialized_end=62
  _globals['_ABRESPONSE']._serialized_start=64
  _globals['_ABRESPONSE']._serialized_end=96
  _globals['_FACTORIALREQUEST']._serialized_start=98
  _globals['_FACTORIALREQUEST']._serialized_end=132
  _globals['_FACTORIALRESPONSE']._serialized_start=134
  _globals['_FACTORIALRESPONSE']._serialized_end=169
  _globals['_TEXTREQUEST']._serialized_start=171
  _globals['_TEXTREQUEST']._serialized_end=198
  _globals['_LETTERRESPONSE']._serialized_start=200
  _globals['_LETTERRESPONSE']._serialized_end=246
  _globals['_ABTESTINGSERVICE']._serialized_start=249
  _globals['_ABTESTINGSERVICE']._serialized_end=457
# @@protoc_insertion_point(module_scope)
