# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import message_service_pb2 as message__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in message_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ABTestingServiceStub(object):
    """Основной сервис с тремя методами для варианта 19
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssignAB = channel.unary_unary(
                '/message.ABTestingService/AssignAB',
                request_serializer=message__service__pb2.ABRequest.SerializeToString,
                response_deserializer=message__service__pb2.ABResponse.FromString,
                _registered_method=True)
        self.Factorial = channel.unary_unary(
                '/message.ABTestingService/Factorial',
                request_serializer=message__service__pb2.FactorialRequest.SerializeToString,
                response_deserializer=message__service__pb2.FactorialResponse.FromString,
                _registered_method=True)
        self.MostFrequentLetter = channel.unary_unary(
                '/message.ABTestingService/MostFrequentLetter',
                request_serializer=message__service__pb2.TextRequest.SerializeToString,
                response_deserializer=message__service__pb2.LetterResponse.FromString,
                _registered_method=True)


class ABTestingServiceServicer(object):
    """Основной сервис с тремя методами для варианта 19
    """

    def AssignAB(self, request, context):
        """Задание 1: A/B тестирование
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Factorial(self, request, context):
        """Задание 2: Факториал
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MostFrequentLetter(self, request, context):
        """Задание 3: Самая частая буква
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ABTestingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssignAB': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignAB,
                    request_deserializer=message__service__pb2.ABRequest.FromString,
                    response_serializer=message__service__pb2.ABResponse.SerializeToString,
            ),
            'Factorial': grpc.unary_unary_rpc_method_handler(
                    servicer.Factorial,
                    request_deserializer=message__service__pb2.FactorialRequest.FromString,
                    response_serializer=message__service__pb2.FactorialResponse.SerializeToString,
            ),
            'MostFrequentLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.MostFrequentLetter,
                    request_deserializer=message__service__pb2.TextRequest.FromString,
                    response_serializer=message__service__pb2.LetterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.ABTestingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('message.ABTestingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ABTestingService(object):
    """Основной сервис с тремя методами для варианта 19
    """

    @staticmethod
    def AssignAB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.ABTestingService/AssignAB',
            message__service__pb2.ABRequest.SerializeToString,
            message__service__pb2.ABResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Factorial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.ABTestingService/Factorial',
            message__service__pb2.FactorialRequest.SerializeToString,
            message__service__pb2.FactorialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MostFrequentLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.ABTestingService/MostFrequentLetter',
            message__service__pb2.TextRequest.SerializeToString,
            message__service__pb2.LetterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
