# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"\x1a\n\tDataPoint\x12\r\n\x05value\x18\x01 \x01(\x05\"&\n\x06Result\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x12\x0f\n\x07\x61verage\x18\x02 \x01(\x02\x32:\n\rDataProcessor\x12)\n\x10ProcessDataBatch\x12\n.DataPoint\x1a\x07.Result(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAPOINT']._serialized_start=14
  _globals['_DATAPOINT']._serialized_end=40
  _globals['_RESULT']._serialized_start=42
  _globals['_RESULT']._serialized_end=80
  _globals['_DATAPROCESSOR']._serialized_start=82
  _globals['_DATAPROCESSOR']._serialized_end=140
# @@protoc_insertion_point(module_scope)
